let arrayPeliculas = [
    {
      id: 'tt0111161',
      title: "The Shawshank Redemption",
      year: 1994,
      director: "Frank Darabont",
      duration: 2.22,
      genre: "Drama",
      score: 9.3,
    },
    {
      id: 'tt0068646',
      title: "The Godfather",
      year: 1972,
      director: "Francis Ford Coppola",
      duration: 2.55,
      genre: "Crime",
      score: 9.2,
    },
    {
      id: 'tt0071562',
      title: "The Godfather: Part II",
      year: 1974,
      director: "Francis Ford Coppola",
      duration: 3.22,
      genre: "Crime",
      score: 9,
    },
    {
      id: 'tt0468569',
      title: "The Dark Knight",
      year: 2008,
      director: "Christopher Nolan",
      duration: 2.32,
      genre: "Action",
      score: 9,
    },
    {
      id: 'tt1856101',
      title: "Blade Runner 2049",
      year: 2017,
      director: "Denis Villeneuve",
      duration: 2.44,
      genre: "Mistery",
      score: 8.5,
    },
    {
      id: 'tt0088763',
      title: "Back to the Future",
      year: 1985,
      director: "Robert Zemeckis",
      duration: 1.56,
      genre: "Adventure",
      score: 8.5,
    },
    {
      id: 'tt0118715',
      title: "The Big Lebowski",
      year: 1998,
      director: "Joel Coen",
      duration: 1.57,
      genre: "Comedy",
      score: 8.2,
    },
    {
      id: 'tt2267998',
      title: "Gone Girl",
      year: 2014,
      director: "David Fincher",
      duration: 2.29,
      genre: "Thriller",
      score: 8.1,
    },
    {
      id: 'tt0086250',
      title: 'Scarface',
      year: 1983,
      director: 'Brian De Palma',
      duration: 2.50,
      genre: 'Crime',
      score: 8.3
    },
    {
      id: 'tt1345836',
      title: 'The Dark Knight Rises',
      year: 2012,
      director: 'Christopher Nolan',
      duration: 2.44,
      genre: 'Action',
      score: 8.4
    },
  ];